2025-08-04 19:20:43,444 - INFO - A new study created in Journal with name: model-population-gkan-population_gkan_repr
2025-08-04 19:20:43,653 - WARNING - Trial 0 failed with parameters: {'lr': 0.0028057582076672534, 'lamb': 1.0, 'batch_size': 16, 'use_orig_reg': True, 'lamb_g_net': 8.63200816860254e-06, 'lamb_h_net': 8.629132190071855e-06, 'grid_size_g_net': 5, 'spline_order_g_net': 3, 'range_limit_g_net': 7, 'mu_1_g_net': 0.8, 'mu_2_g_net': 0.1, 'hidden_dim_g_net': 6, 'grid_size_h_net': 18, 'spline_order_h_net': 1, 'range_limit_h_net': 2, 'mu_1_h_net': 0.2, 'mu_2_h_net': 0.4, 'hidden_dim_h_net': 4} because of the following error: OSError(5, 'Input/output error').
Traceback (most recent call last):
  File "/home/ricca/miniconda3/envs/myenv/lib/python3.12/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/home/ricca/Kan-for-Interpretable-Graph-Dynamics/experiments/Experiments.py", line 261, in objective
    print(f"Trial {trial.number}: num params: {total_params}")
OSError: [Errno 5] Input/output error
2025-08-04 19:20:43,654 - WARNING - Trial 0 failed with value None.
